Мелкоштуки
Proxima-Project/Proxi-BoS-Bay12 pull request #38
Opened 2022-08-06 15:04 UTC by Kolergo

На Эллипс добавлены термалочки, штука для надувных стен и бинокль. Удалён уран что валялся на полу. Оутфиты и декали всё ещё сломаны да
На много увеличен шанс появления смешной контрабанды, вместо обычной.

2022-08-06 17:39 UTC, ActuallyALovelyGrave commented
1.Термалки удалены со всех авеек бэя в виду имбалансности и "no-fun to play against". Вспоминая, что на Элипсе был рельсотрон - это как минимум неправильно. Даже для одного.
2. Ты точно проверил что в этой контробанде не спавнится аплинк?

2022-08-06 17:56 UTC, Kolergo commented
> 1.Термалки удалены со всех авеек бэя в виду имбалансности и "no-fun to play against". Вспоминая, что на Элипсе был рельсотрон - это как минимум неправильно. Даже для одного. 2. Ты точно проверил что в этой контробанде не спавнится аплинк?

1. Удалены скорее из-за того что бэй очень не любит авейки. Рельсатрон действительно крутой, но у оператора всё ещё очень хиленькая броня, а его кораблик и его самого может снести одна-две ЭМИ ракеты, которым он не сможет ничего противопоставить. 
2. Я лично внёс аплинк в список спавнищихся вещей, а что?

2022-08-06 18:06 UTC, ActuallyALovelyGrave commented
1. Я помню у него была своя броня что имела статы под 70+, что хиленькой не назовешь. Может и путаю.
1.1 Нет, просто когда скреллы/какая-либо иная авейка начинают стрелять через 7 стен, а игроки ему сделать ничего не могут, это неправильно. Унификация баланса, все дела.
1.2 - Уявзимость корабля решается маневрами и щитами, которые есть.
~~2. Антаги конечно заревут, когда узнают, что после такого у всего отряда морпехов будет по термалке, ehh.~~

2022-08-06 18:16 UTC, Kolergo commented
> 1. Я помню у него была своя броня что имела статы под 70+, что хиленькой не назовешь. Может и путаю.
>    1.1 Нет, просто когда скреллы/какая-либо иная авейка начинают стрелять через 7 стен, а игроки ему сделать ничего не могут, это неправильно. Унификация баланса, все дела.
>    1.2 - Уявзимость корабля решается маневрами и щитами, которые есть.
>    ~2. Антаги конечно заревут, когда узнают, что после такого у всего отряда морпехов будет по термалке, ehh.~

1. 70+ ? Тоже могу путать, но по моему у неё защита только от балистики нормальная, на уровне СБшной брони. От энергетической(воксы, аскенты) слабенькое. А шлем вообще лопается от одного удара(гиб башки может и не убивает ИПС, но делает его слепым, чего вполне достаточно).
1.1 Сейчас чекну броню - если она действительно не так слаба как я думал то замену на мезонки(кому они нужны...)
1.2 Помнится мне что ЭМИ сшибает щиты. А вместе с ними и нашего робочубрика сшибет.
2. По идее аплинк должен спавниться раз в три раунда с контрабандой, что редко(хотя конечно вероятность та ещё штука). Так что всё зависит от везения игроков. Аплинк может и антаг найти и плакать уже будут марины с СБ. Или его найдёт вокс безбилетник и начнёт смешное.

2022-08-06 18:22 UTC, Kolergo commented
Броню чекнул, он действительно крепкая. Вот так и верь кодексу. Меняю термалы на мезонки

2022-08-10 11:23 UTC, HaCsO commented
у меня один вопрос. почему в pick насрано путями? трудно было сделать одну переменную список со всеми требуемыми путями?

2022-08-10 11:26 UTC, Kolergo commented
Да

2022-08-11 13:47 UTC, HaCsO requested changes

2022-08-11 13:47 UTC, HaCsO commented on code/modules/aspects/contraband.dm
> +	var/contraband_common_list = list(/obj/random/lilgun, /obj/random/contraband, /obj/random/contraband, /obj/random/contraband)
var/list/contraband_common_list

2022-08-11 13:48 UTC, Kolergo commented on code/modules/aspects/contraband.dm
> +	var/contraband_common_list = list(/obj/random/lilgun, /obj/random/contraband, /obj/random/contraband, /obj/random/contraband)
ladno

2022-08-11 13:51 UTC, merged