Фиксы ГКК и Шеллов
Proxima-Project/Proxi-BoS-Bay12 pull request #82
Opened 2022-09-30 22:38 UTC by Evie7056

ГККшники получили свою личную частоту.
Охрана представителя получила свои законные шкафчики на место с плитники, а также "церемониальной лазерной винтовкой". Ее однозначно не спиздили из ЦПСС, да.
Шеллы научились надевать большинство ригов снова. Пожалуйста, не надо спрашивать, откуда в ригах для шеллов были дырки для хвостов, мы не знаем. ((это все хестия))

2022-09-30 23:40 UTC, Evie7056 commented
ППшки и частота еще не работают

2022-10-01 10:12 UTC, actuallynotajoke commented
почему конфликты и почему приколы с тестами

2022-10-01 10:16 UTC, Evie7056 commented
Приду домой - посмотрю. Либо это с пром Гуся конфликт, либо с пром колерго. В любом случае, думаю не критично

2022-10-01 10:17 UTC, Evie7056 commented
А, а ещё я ночью запушмла коммит с синтаксической ошибкой. Похуй+похуй. Просто не мержи это

2022-10-02 18:53 UTC, Archemagus requested changes
Рья
https://github.com/Proxima-Project/Proxi-BoS-Bay12/blob/dev/maps/torch/items/machinery.dm#L33

2022-10-02 18:53 UTC, Archemagus commented on code/modules/mob/living/say.dm
> +  	  ":п" = "Terran",		".п" = "Terran",	//Bos
В листе даже у коментариев должны быть запятые

2022-10-02 18:53 UTC, Archemagus commented on code/modules/mob/living/say.dm
> +   	  ":П" = "Terran",		".П" = "Terran",	//Bos
Тут тоже запятую после коментариев.
Это нужно чтобы проверка кода не сошла с ума, т.к. она слишком тупая чтобы различать коментарий и актуальный код

2022-10-02 18:53 UTC, Archemagus commented on maps/torch/structures/closets/misc.dm
> +			/obj/item/clothing/suit/armor/pcarrier/medium,
Что за табы смешные, а ну все ровно в ряд

2022-10-02 18:53 UTC, Archemagus commented on proxima/code/game/items/weapons/projectile/infinity-ammuntion.dm
> +	desc = "A high-powered bullet casing. Somwewhat between 7-8mm."
~~прочитал как "копро" в целом так оно и есть. Мьех~~

2022-10-02 18:53 UTC, Archemagus commented on code/modules/boh/fabrication/weaponsfab.dm
> +	req_access = null
Вместо null лучше писать просто пустой лист list()
also зачем РНД фабрикатор без ограничений доступа? Я думал что они будут печатать фабрикаторы залоченные за СБшниками, чтобы не было пушек в РнД. В этом вообще смысл фабрикатора.

А сама плата на случай если в оружейке разьебут основной?

2022-10-02 18:53 UTC, Archemagus commented on code/game/machinery/telecomms/presets.dm
> +	freq_listening = list(AI_FREQ, SCI_FREQ, MED_FREQ,TERR_FREQ, SUP_FREQ, SRV_FREQ, COMM_FREQ, ENG_FREQ, SEC_FREQ, INF_FREQ, ENT_FREQ, HAIL_FREQ) //inf_freq, TERR_FREQ - bos
```suggestion
	freq_listening = list(AI_FREQ, SCI_FREQ, MED_FREQ, TERR_FREQ, SUP_FREQ, SRV_FREQ, COMM_FREQ, ENG_FREQ, SEC_FREQ, INF_FREQ, ENT_FREQ, HAIL_FREQ) //inf_freq, TERR_FREQ - bos
```

2022-10-02 18:53 UTC, Archemagus commented on code/controllers/communications.dm
> +	"Recon"			= SKRELL_FREQ, //boh
```suggestion
	"Recon"			= SKRELL_FREQ, //boh,
```

2022-10-02 18:53 UTC, Archemagus commented on code/game/machinery/telecomms/presets.dm
> +	freq_listening = list(SEC_FREQ, COMM_FREQ, INF_FREQ, TERR_FREQ) //inf_freq, TERR_FREQ - bos
```suggestion
	freq_listening = list(SEC_FREQ, COMM_FREQ, INF_FREQ, TERR_FREQ) //inf_freq, TERR_FREQ - bos,
```

2022-10-02 18:53 UTC, Archemagus commented on code/modules/mob/living/say.dm
> +	  ":g" = "Terran",		".g" = "Terran",	//Bos
```suggestion
	  ":g" = "Terran",		".g" = "Terran",	//Bos,
```

2022-10-02 18:53 UTC, Archemagus commented on code/modules/mob/living/say.dm
> +	  ":G" = "Terran",		".G" = "Terran",	//Bos
```suggestion
	  ":G" = "Terran",		".G" = "Terran",	//Bos,
```

2022-10-02 18:53 UTC, Archemagus commented on code/modules/mob/living/say.dm
> +  	  ":п" = "Terran",		".п" = "Terran",	//Bos
```suggestion
  	  ":п" = "Terran",		".п" = "Terran",	//Bos,
```

2022-10-02 18:53 UTC, Archemagus commented on code/modules/mob/living/say.dm
> +   	  ":П" = "Terran",		".П" = "Terran",	//Bos
```suggestion
   	  ":П" = "Terran",		".П" = "Terran",	//Bos,
```

2022-10-02 18:53 UTC, Archemagus commented on maps/torch/structures/closets/misc.dm
> +	req_access = list(access_representative)	// Why here was Science "Security Guard" Access anyway? -laxesh //who cares, this fucking locker wasn't even used, bruh. -evie
```suggestion
	req_access = list(access_representative)
```
BRUH

2022-10-02 18:55 UTC, Evie7056 commented on code/modules/boh/fabrication/weaponsfab.dm
> +	req_access = null
Кейк сказал, что пусть уж ученые делают оружия. На босе живем.

2022-10-02 20:06 UTC, Evie7056 commented
оно готовое и работает.

2022-10-02 20:08 UTC, merged