Купили лорнет
Proxima-Project/Proxi-BoS-Bay12 pull request #87
Opened 2022-10-04 14:53 UTC by Kolergo

Меняю упоминания нтнета на лорнет и названия программ.  Попутно добавил смешные имена боссов в аркаду. 

Пока не хватает двух картинок для замены буквы Н в аплинке ри вне его. Вообщем жду

2022-12-06 10:23 UTC, Kolergo commented
Ну и где мержи, я уже вкодил суда петлю

2022-12-06 12:01 UTC, SidVeld commented
> Ну и где мержи, я уже вкодил суда петлю

Есть один нюанс

![изображение](https://user-images.githubusercontent.com/22749671/205906408-36c21b22-9725-4657-a3c1-d145549be17b.png)

2022-12-06 12:03 UTC, SidVeld commented
@Kolergo 

![изображение](https://user-images.githubusercontent.com/22749671/205906800-c109f616-0889-4bd7-b83c-b07e0f03a3b3.png)

2022-12-06 12:19 UTC, SidVeld commented
Сейчас попробую кнопками решить конфликт

2022-12-06 12:21 UTC, SidVeld commented
@Kolergo нам нужен файл с петлёй или нет?


![изображение](https://user-images.githubusercontent.com/22749671/205911245-7594f299-1e16-4b89-bd72-c2c6301e55aa.png)

2022-12-06 12:22 UTC, Kolergo commented
Нужен конечно, я его пытался по новой вставить, но не помогло

2022-12-06 12:28 UTC, Kolergo commented
Спасибо всем Сидвельдам

2022-12-15 14:24 UTC, SidVeld commented
Тесты:
```sh
## UNIT_TEST ##: /datum/gear/gloves/biker - /obj/item/clothing/gloves/biker: Did not find the icon state 'biker_fingerless' in the icon 'icons/bos/obj/obj_hands.dmi'.
## UNIT_TEST ##: !!! FAILURE !!! [LOADOUT: Entries shall have valid icon states]: One or more /datum/gear definitions had paths with invalid icon states.
```

И
```
./icons/bos/mob/onmob/species/vox/onmob_head_vox.dmi had too many icon states. 516/512.
```

2022-12-15 14:29 UTC, SidVeld requested changes

2022-12-15 14:29 UTC, SidVeld commented on code/bos/game/objects/noose.dm
> +			return TRUE
Я так понимаю, что это чистый копи-паст, но дело не в этом

Пожалуйста, делайте имена переменных чуть сложнее, чтобы можно было понять, что они из себя представляют. Например вместо `var/obj/O` можно использовать `var/obj/Object`

2022-12-15 14:29 UTC, SidVeld commented on code/modules/modular_computers/file_system/programs/generic/game.dm
>  	return "[name_part1] [name_part2]"
Простите, но почему Борис Букер и Стивен должны участвовать в генережке имени врага?

2022-12-15 14:30 UTC, SidVeld commented on code/bos/game/objects/noose.dm
> +			return TRUE
К слову это не очень важно

2022-12-15 14:30 UTC, SidVeld commented on code/modules/modular_computers/file_system/programs/generic/game.dm
>  	return "[name_part1] [name_part2]"
***А ВОТ ЭТО ВАЖНО***

2022-12-15 14:31 UTC, Kolergo commented on code/modules/modular_computers/file_system/programs/generic/game.dm
>  	return "[name_part1] [name_part2]"
Пиратская игра, ИЦ причина для расстрелов

2022-12-15 14:31 UTC, Kolergo commented on code/bos/game/objects/noose.dm
> +			return TRUE
Злобный инфинити код

2022-12-15 14:37 UTC, Kolergo commented on code/modules/modular_computers/file_system/programs/generic/game.dm
>  	return "[name_part1] [name_part2]"
Я извиняюсь перед Борисом Букером

2022-12-15 14:38 UTC, Kolergo commented
> Тесты:
> 
> ```shell
> ## UNIT_TEST ##: /datum/gear/gloves/biker - /obj/item/clothing/gloves/biker: Did not find the icon state 'biker_fingerless' in the icon 'icons/bos/obj/obj_hands.dmi'.
> ## UNIT_TEST ##: !!! FAILURE !!! [LOADOUT: Entries shall have valid icon states]: One or more /datum/gear definitions had paths with invalid icon states.
> ```
> 
> И
> 
> ```
> ./icons/bos/mob/onmob/species/vox/onmob_head_vox.dmi had too many icon states. 516/512.
> ```

До меня ещё было, Коисцин там что-то сделал

2022-12-15 15:29 UTC, SidVeld approved these changes
Теперь у тебя +10 социального кредита

2022-12-15 15:30 UTC, merged